[package]
name = "wiry"
version = "0.1.0"
authors = ["Michael Palmos <toqoz@hotmail.com>"]
edition = "2018"

[dependencies]
#glutin = "*"
winit = "0.19.1"
x11 = { version = "2.18.1", features = ["xlib"] }
dbus = "0.6.4"
toml = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
#gl = "0.6.0"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["ttf", "gfx"]
