[package]
name = "wired"
version = "0.8.0"
authors = ["Michael Palmos <toqoz@hotmail.com>"]
edition = "2018"

[dependencies]
wired_derive = { path = "./wired_derive" }

winit = "0.21.0"
x11 = { version = "2.18.1", features = ["xlib"] }
dbus = "0.8.2"
image = "0.22.2"
ron = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
pango = "0.6.0"
pangocairo = "0.7.0"
cairo-rs = "0.6.0"
cairo-sys-rs = { version = "0.8.0", features = ["xlib"] }
xdg = "2.2.0"
notify = "4.0.15"
bitflags = "1.2"
