[package]
name = "wiry"
version = "0.1.0"
authors = ["Michael Palmos <toqoz@hotmail.com>"]
edition = "2018"

[dependencies]
#winit = "0.20.0-alpha3"
winit = "0.21.0"
#winit = { path = "../winit" }
x11 = { version = "2.18.1", features = ["xlib"] }
dbus = "0.6.4"
#toml = "0.5.0"
image = "0.22.2"
ron = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
pango = "0.6.0"
pangocairo = "0.7.0"
cairo-rs = "0.6.0"
cairo-sys-rs = { version = "0.8.0", features = ["xlib"] }
