max_notifications = 4
gap = 8

[notification]
width = 300
height = 100
x = 10
y = 874

border_width = 3

background_color = { r = 0.15686, g = 0.15686, b = 0.15686, a = 1.0 }
border_color = { r = 0.92157, g = 0.858824, b = 0.698039, a = 1.0 }

timeout = 10.0

scroll_speed = 1.0
bounce = false

[notification.summary]
anchor = "Root"                 # "Root", "Summary", or "Body".  Don't select "Summary" for the summary.
anchor_position = "Left"     # "TopLeft", "TopRight", "BottomLeft", or "BottomRight".

font = "Arial 11"

color = { r = 0.92157, g = 0.858824, b = 0.698039, a = 1.0 }

width = 78
max_lines = 1

left_margin = 8
right_margin = 8
top_margin = 8
bottom_margin = 8

[notification.body]
anchor = "Summary"                 # "Root", "Summary", or "Body".  Don't select "Summary" for the summary.
anchor_position = "Right"          # "Left", "Right", "Top", or "Bottom".

font = "Arial 11"

color = { r = 0.92157, g = 0.858824, b = 0.698039, a = 1.0 }

width = 200
max_lines = 1

left_margin = 8
right_margin = 8
top_margin = 8
bottom_margin = 8


[shortcuts]
# TODO= use real values here
notification_close = 1
notification_closeall = 2
notification_pause = 3
notification_url = 4

